= Contributing to Labs Ubiquitous Journey 
:toc:
:toc-title:
:toc-placement!:

Thanks for checking out the Labs Ubiquitous Journey guides! We’re excited to hear
and learn from you. Your experiences will benefit others who read and
use these guides.

We’ve put together the following guidelines to help you figure out where
you can best be helpful.

toc::[]

== Types of contributions we’re looking for

This project is used as a starting point for CI/CD tooling and others by the 
Red Hat Open Innovation Labs group. It incoporates many technologies
and is intended for development on OpenShift Container Platform.

Interested in making a contribution? Read on!

== Ground rules & expectations

Before we get started, here are a few things we expect from you (and
that you should expect from others):

* Be kind and thoughtful in your conversations around this project. We
all come from different backgrounds and projects, which means we likely
have different perspectives on "how open source is done". Try to
listen to others rather than convince them that your way is correct.
* There is a
link:./CODE_OF_CONDUCT.md[Contributor Code of Conduct]. By participating
in this project, you agree to abide by its terms.
* If you open a pull request, please ensure that your contribution
passes all tests. If there are test failures, you will need to address
them before we can merge your contribution.

== Getting set up for local development

Local Development guide is still under construction...

=== Deploying to OpenShift 

The Labs Ubiquitous Journey stack can be deployed to any OpenShift cluster
Just follow the README for instructions

== Contributing Content

If you’d like to contribute, start by searching through the GitHub
https://github.com/rht-labs/labs-ci-cd/issues[issues] and
https://github.com/rht-labs/labs-ci-cd/pulls[pull requests] to see
whether someone else has raised a similar idea or question.

If you don’t see your idea listed, and you think it fits into the goals
of this guide, do one of the following: * *If your contribution is
minor,* such as a typo fix, open a pull request. * *If your contribution
is major,* such as a new article or category, start by opening an issue
first. That way, other people can weigh in on the discussion before you
do any work.

== Contribution review process

This repo is currently maintained by @springdo, @pcarney8, @eformat @tylerauerbeck, and
@ckavili, who have commit access. They will likely review your
contribution. If you haven’t heard from anyone in 10 days, feel free to
bump the thread or @-mention a maintainer or
`@rht-labs/OpenInnovationLabs` to review your contribution.

== Community

Discussions about Labs Ubiquitous Journey takes place within this repository’s
https://github.com/rht-labs/ubiquitous-journey/issues[Issues] and
https://github.com/rht-labs/ubiquitous-journey/pulls[Pull Requests]
sections.
 
Wherever possible, do not take these conversations to private channels,
including contacting the maintainers directly. Keeping communication
public means everybody can benefit and learn from the conversation.
