apiVersion: v2
name: ubiquitous-journey
description: A Helm chart for ubiquitous-journey 
type: application

# This is the chart version. This version number should be incremented each time you make changes
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
appVersion: 0.0.1

dependencies:
- name: argo-cd
  version: "2.0.0"
  repository: "https://tylerauerbeck.github.io/argo-helm"
  condition: argo-cd.enabled
