
argo-cd:
  enabled: true
  installCRDs: false

  global:
# Do we want this?
    clusterAdminAccess:
      enabled: true

  dex:
    image:
      tag: v2.22.0

  server:
    extraArgs: {insecure: true }
    route:
      enabled: true
      termination_type: edge
      termination_policy: Redirect

  configs:
    argocdServerAdminPassword: $2a$10$/R5V2T4y23yQL9y0aqt3x.d.QQ5XSCsUr2IebD6XFt9ii5I17AOx.

  openshift:
    enabled: true
